### ISSUE TITLE
API Docs and DB Diagram

### ISSUE THREAD

**Issue by AnthonyBronca** [surnan/air-sea-and-see#1]
# DB Diagram:
Some small adjustments needed, however, without changing some of the current items would cause big bugs in the future

## Tasks: 
- [x] Readjust the way we are handling previewImage on `Spots` . We have an associated table we can use to create more than one `preview` down the line
- [x] Remove `reviewImageId` from `Reviews`. `Reviews` is the parent table, and it should be passing it’s `id` to the child table `Review Images` , which is also missing an attribute to receive foreign keys from the parent.

# API Docs:
We want to work with a family hierarchy. Example: `<parents>/<parent>/<children>/<child>` . If the route will have grand children, we can omit grand parents to keep `parents/children` style. Notice where the plurals are, and remember we may handle selecting a singular parent/child using `:ids`

## Tasks: 
- [x] Adjust routes that seem to be missing. Example: Log in User
- [x] Refactor Sign up a User to be /signup
- [x] Readjust routes to be RESTFUL. Example: Get all the Spots owned by the Current User should be something like /users/:userId/spots
- [x] Review all routes

# Deadline:
Please aim to complete the listed tasks by EOD on Monday, May 13th as we are looking to have all documentations approved in order to move on to the next phase of our project life cycle the following day.

**Comment by irelius** [comment]
# API Docs and DB Diagram Review 2

## DB Diagram
- [ ] "spotImage" under the SpotImages table should be called something else. Foreign keys uses the primary key (the id of another table). You have the naming convention correct in your other foreign keys.
- [ ] "reviewId" under the ReviewImages table should be a different datatype

## API Docs
Looks all good. Nice work!

Something you can think about is how the ReviewImages and SpotImages tables are separate tables that handle storing the images for Reviews and Spots respectively. Because of this, you can shorten the routes for "Delete a Spot Image" and "Delete a Review Image". If you know that you'll get an image for a review anytime you query the ReviewImages table, you don't need to worry about including that detail in the API endpoint (same goes for SpotImages). However, ywould need to revise the route to be descriptive for which table you'd be querying.
How you have your route won't break, you can leave as is.

**Comment by AnthonyBronca** [comment]
Closed, Looks good!
