### ISSUE TITLE
Create Migration and Models for DB

### ISSUE THREAD

**Issue by surnan** [surnan/air-sea-and-see#8]
# Create Migration and Models for DB
##
### Tasks
- [ ] Create sequelize migrations
- [ ] Create sequelize models
- [ ] Create sequelize seeder files
